### ISSUE TITLE
Make `symbolizer-rs` a library rather than an executable

### ISSUE THREAD

**Issue by hugsy** [0vercl0k/symbolizer-rs#2]
Improvement suggestion: `symbolizer-rs` could be beneficial as a library (with the executable parser as an [example](https://doc.rust-lang.org/cargo/reference/cargo-targets.html#examples)) would be really convenient for integration to other projects.

**Comment by 0vercl0k** [comment]
Yeah I think that'd be good. I'm going to wait a bit to iron out the first few bugs but when the dust settles, let's talk :)

**Comment by 0vercl0k** [comment]
I think I'll look at that this month hopefully @hugsy - let me know if you have specific requests / usages in mind so that I can do my best to account for it :)

Cheers

**Comment by hugsy** [comment]
> let me know if you have specific requests / usages in mind

Considering it's the only lib (AFAIK) that's cross-platform to symbolize traces, it'd really nice to use it in other languages than Rust, at least with C/C++ via FFI and ideally Python. Personally my (immediate) usage would be Python but I realize it could be too much to ask, so if you can make a lib (first) with FFI (second), I'm happy to contribute and PR some Py bindings.

What do you think ?

**Comment by 0vercl0k** [comment]
Ack yeah, let me first find time make the lib as you mentioned : D

**Comment by 0vercl0k** [comment]
Okay I've pushed up [addr-symbolizer](https://crates.io/crates/addr-symbolizer) - sorry for the long delay (I lost motivation on the way 😅). There are probably a bunch of rough edges but .. yeah!

Cheers
