### ISSUE TITLE
PDB from my custom location

### ISSUE THREAD

**Issue by ahpaleus** [0vercl0k/symbolizer-rs#6]
Hey, when I try to load a PDB file from the `_NT_SYMBOL_PATH` (or `--symcache`), symbolizer-rs does not resolve symbols for my custom `*.sys` - still shows like `module.sys+0x1337`. How to do that? It resolves standard ones correctly (like `ntoskrnl.exe!KiPageFault`).

**Comment by ahpaleus** [comment]
At least I was able to overcome it by providing incorrect path to the --symsrv, then grabbing the path with 'hash' and adding it correctly to the symcache directory :-)

**Comment by 0vercl0k** [comment]
Thanks for the report & for trying it out🙏🏽!

This is not the user experience I am shooting for 😂 let me take a quick look..

Cheers

**Comment by 0vercl0k** [comment]
Okay so the `--symcache` is where the downloaded PDB files will be written to and it is also where it'll check for their existence before downloading them (`--symsrv` is where to download them from).

But it does require that this directory is formatted like a symbol cache which means a directory with the PDB file name, hash, etc.

So I guess in your case you had a directory with 'just' a PDB file?

Cheers

**Comment by 0vercl0k** [comment]
I am thinking to add an 'import' option that'd properly drop all PDBs found in the `symcache` if appropriate; wdyt?

Cheers

**Comment by 0vercl0k** [comment]
I've prototyped the above @ahpaleus - I'd appreciate if you could give it a shot and let me know if it works out for you :).

Here is an example:
```
symbolizer-rs>dir c:\users\over\downloads\y
08/11/2024  08:08 PM         1,551,360 ntdll.pdb

symbolizer-rs>dir c:\users\over\downloads\x
08/11/2024  07:50 PM         7,719,936 ntkrnlmp.pdb

symbolizer-rs>cargo run -- --import-pdbs c:\Users\over\Downloads\x --import-pdbs c:\Users\over\Downloads\y --symcache c:\Users\over\Downloads\tmp --trace c:\work\foo.trace --limit 1000
...
✓ Successfully symbolized 1.0k lines across 1.0 files in 15.0s (12% cache hits)
```

And the output w/o importing PDBs and an empty cache (notice the `downloaded 8.8mb / 2.0 PDBs` at the end):
```
symbolizer-rs>cargo run -- --symcache c:\Users\over\Downloads\tmp --trace c:\work\foo.trace --limit 1000
...
✓ Successfully symbolized 1.0k lines across 1.0 files in 24.0s (12% cache hits, downloaded 8.8mb / 2.0 PDBs)
```

And you can try out the fix with:
```
$ git checkout fbl_libify
$ cargo r -r -- --help
```

Cheers

**Comment by ahpaleus** [comment]
Works as a charm. Thank you!

**Comment by 0vercl0k** [comment]
Awesome, thank you - closing this then :)

Cheers
